const Books=
  [
    {
      "id": "b1",
      "title": "Dune",
      "author": "Frank Herbert",
      "category": "Sci-Fi",
      "categoryId": "c1",
      "coverImage": "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400&q=80",
      "publishedYear": 1965,
      "rating": 4.8,
      "isAvailable": true,
      "description": "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world."
    },
    {
      "id": "b2",
      "title": "Project Hail Mary",
      "author": "Andy Weir",
      "category": "Sci-Fi",
      "categoryId": "c1",
      "coverImage": "https://images.unsplash.com/photo-1614729939124-03290b56c9ce?w=400&q=80",
      "publishedYear": 2021,
      "rating": 4.7,
      "isAvailable": true,
      "description": "A lone astronaut must save the earth from disaster in this incredible science-based thriller."
    },
    {
      "id": "b3",
      "title": "The Martian",
      "author": "Andy Weir",
      "category": "Sci-Fi",
      "categoryId": "c1",
      "coverImage": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&q=80",
      "publishedYear": 2011,
      "rating": 4.6,
      "isAvailable": false,
      "description": "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there."
    },
    {
      "id": "b4",
      "title": "Neuromancer",
      "author": "William Gibson",
      "category": "Sci-Fi",
      "categoryId": "c1",
      "coverImage": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&q=80",
      "publishedYear": 1984,
      "rating": 4.3,
      "isAvailable": true,
      "description": "The Matrix is a world within the world, a global consensus-hallucination. Henry Dorsett Case was the sharpest data-thief in the business."
    },
    {
      "id": "b5",
      "title": "The Midnight Library",
      "author": "Matt Haig",
      "category": "Fantasy",
      "categoryId": "c2",
      "coverImage": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
      "publishedYear": 2020,
      "rating": 4.5,
      "isAvailable": true,
      "description": "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life."
    },
    {
      "id": "b6",
      "title": "The Hobbit",
      "author": "J.R.R. Tolkien",
      "category": "Fantasy",
      "categoryId": "c2",
      "coverImage": "https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=400&q=80",
      "publishedYear": 1937,
      "rating": 4.9,
      "isAvailable": true,
      "description": "A great modern classic and the prelude to The Lord of the Rings. Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life."
    },
    {
      "id": "b7",
      "title": "The Name of the Wind",
      "author": "Patrick Rothfuss",
      "category": "Fantasy",
      "categoryId": "c2",
      "coverImage": "https://images.unsplash.com/photo-1629196914214-4196144e542e?w=400&q=80",
      "publishedYear": 2007,
      "rating": 4.8,
      "isAvailable": false,
      "description": "Told in Kvothe's own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen."
    },
    {
      "id": "b8",
      "title": "Mistborn: The Final Empire",
      "author": "Brandon Sanderson",
      "category": "Fantasy",
      "categoryId": "c2",
      "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80",
      "publishedYear": 2006,
      "rating": 4.7,
      "isAvailable": true,
      "description": "In a world where ash falls from the sky, a brilliant thief and a powerful street urchin plan a heist to overthrow a dark lord."
    },
    {
      "id": "b9",
      "title": "Eloquent JavaScript",
      "author": "Marijn Haverbeke",
      "category": "Programming",
      "categoryId": "c3",
      "coverImage": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&q=80",
      "publishedYear": 2018,
      "rating": 4.7,
      "isAvailable": true,
      "description": "A modern introduction to programming diving deep into the JavaScript language to show you how to write beautiful, effective code."
    },
    {
      "id": "b10",
      "title": "Learning React",
      "author": "Alex Banks & Eve Porcello",
      "category": "Programming",
      "categoryId": "c3",
      "coverImage": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&q=80",
      "publishedYear": 2020,
      "rating": 4.6,
      "isAvailable": true,
      "description": "If you want to learn how to build efficient user interfaces with React, this is your step-by-step guide to modern web development."
    },
    {
      "id": "b11",
      "title": "PHP & MySQL: Novice to Ninja",
      "author": "Tom Butler",
      "category": "Programming",
      "categoryId": "c3",
      "coverImage": "https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?w=400&q=80",
      "publishedYear": 2017,
      "rating": 4.4,
      "isAvailable": false,
      "description": "A practical, hands-on guide to learning all the tools, principles, and techniques needed to build a professional web application."
    },
    {
      "id": "b12",
      "title": "HTML and CSS: Design and Build Websites",
      "author": "Jon Duckett",
      "category": "Programming",
      "categoryId": "c3",
      "coverImage": "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=400&q=80",
      "publishedYear": 2011,
      "rating": 4.8,
      "isAvailable": true,
      "description": "A highly visual, beautifully designed book that introduces HTML and CSS in a way that makes them accessible to everyone."
    },
    {
      "id": "b13",
      "title": "The Silent Patient",
      "author": "Alex Michaelides",
      "category": "Mystery",
      "categoryId": "c4",
      "coverImage": "https://images.unsplash.com/photo-1587876931567-564ce588bfbd?w=400&q=80",
      "publishedYear": 2019,
      "rating": 4.3,
      "isAvailable": true,
      "description": "A shocking psychological thriller of a woman's act of violence against her husband—and of the therapist obsessed with uncovering her motive."
    },
    {
      "id": "b14",
      "title": "Gone Girl",
      "author": "Gillian Flynn",
      "category": "Mystery",
      "categoryId": "c4",
      "coverImage": "https://images.unsplash.com/photo-1476275466078-4007374efac4?w=400&q=80",
      "publishedYear": 2012,
      "rating": 4.4,
      "isAvailable": true,
      "description": "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne's fifth wedding anniversary. And Amy is gone."
    },
    {
      "id": "b15",
      "title": "And Then There Were None",
      "author": "Agatha Christie",
      "category": "Mystery",
      "categoryId": "c4",
      "coverImage": "https://images.unsplash.com/photo-1518379469505-0a75f1df6469?w=400&q=80",
      "publishedYear": 1939,
      "rating": 4.9,
      "isAvailable": false,
      "description": "Ten strangers are invited to an isolated island mansion. One by one, they are murdered in accordance with a sinister nursery rhyme."
    },
    {
      "id": "b16",
      "title": "The Da Vinci Code",
      "author": "Dan Brown",
      "category": "Mystery",
      "categoryId": "c4",
      "coverImage": "https://images.unsplash.com/photo-1605494493390-349f257a0701?w=400&q=80",
      "publishedYear": 2003,
      "rating": 4.2,
      "isAvailable": true,
      "description": "A murder in the Louvre Museum reveals a sinister plot to uncover a secret that has been protected by a clandestine society since the days of Christ."
    },
    {
      "id": "b17",
      "title": "Sapiens: A Brief History of Humankind",
      "author": "Yuval Noah Harari",
      "category": "History",
      "categoryId": "c5",
      "coverImage": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80",
      "publishedYear": 2011,
      "rating": 4.8,
      "isAvailable": true,
      "description": "A bold, wide-ranging narrative that traces human evolution from the Stone Age up to the twenty-first century."
    },
    {
      "id": "b18",
      "title": "SPQR: A History of Ancient Rome",
      "author": "Mary Beard",
      "category": "History",
      "categoryId": "c5",
      "coverImage": "https://images.unsplash.com/photo-1552214470-4cb7ce8812f8?w=400&q=80",
      "publishedYear": 2015,
      "rating": 4.5,
      "isAvailable": true,
      "description": "A sweeping, revisionist history of the Roman Empire from one of our foremost classicists."
    },
    {
      "id": "b19",
      "title": "The Art of War",
      "author": "Sun Tzu",
      "category": "History",
      "categoryId": "c5",
      "coverImage": "https://images.unsplash.com/photo-1590424754705-728b705bd2d7?w=400&q=80",
      "publishedYear": -500,
      "rating": 4.6,
      "isAvailable": true,
      "description": "An ancient Chinese military treatise dating from the Late Spring and Autumn Period, consisting of 13 chapters devoted to aspects of warfare."
    },
    {
      "id": "b20",
      "title": "Guns, Germs, and Steel",
      "author": "Jared Diamond",
      "category": "History",
      "categoryId": "c5",
      "coverImage": "https://images.unsplash.com/photo-1461360228754-6e81c478b882?w=400&q=80",
      "publishedYear": 1997,
      "rating": 4.4,
      "isAvailable": false,
      "description": "A short history about everybody for the last 13,000 years, exploring how environmental factors shaped human history across continents."
    }
  ]
export default Books;